### ISSUE TITLE
Problem with the cache in 1.7.4.2

### ISSUE THREAD

**Issue by infinity-web-italy** [PrestaShop/ps_categoryproducts#5] opened 2018-09-18 08:22 UTC
Hello,
I noticed that the module does not work correctly when you activate the theme cache ..
As you can see from the image, the first product is seen correctly while the others do not. If you disable the theme cache this does not happen. This site, however, needs the active cache!
Any ideas on how I can fix this problem?
![1](https://user-images.githubusercontent.com/43369421/45673933-3eb7fb00-bb2c-11e8-8187-7b00379df75b.JPG)

**Comment by khouloudbelguith** [comment] 2018-09-18 08:27
Hi @infinity-web-italy,

We manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9652
So, I close it.
Thanks!

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-09-18 08:27
Duplicate of #9652

**Closed by khouloudbelguith** 2018-09-18 08:27 UTC
